### PR TITLE
Show type of download

### PR DESCRIPTION
**Pull request by RunDevelopment**
When there are multiple download buttons, it will now show the type of the resource.

image

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Actually, there should be different labels. Someone that doesn't know what pytorch, etc. is might think that they will literally download PyTorch/ONNX by clicking on those buttons.

**Review by joeyballentine — APPROVED** [review]

**Comment by joeyballentine** [comment]
Oh yeah good point

**Comment by joeyballentine** [comment]
I always imagined it as having the icon of the framework on the left, and maybe even color coded buttons (though that might be excessive)

**Comment by RunDevelopment** [comment]
More colors will be difficult, but framework icons sound like a good idea.

**Review by joeyballentine — APPROVED** [review]

**Pull request merged**
