### PR TITLE
model card grow effect on hover

### PR DESCRIPTION
**Pull request by joeyballentine**
image

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Not a fan for multiple reasons:
- Hover effects don't work well on touch devices. So changing size on hover can be confusing for users on touch devices.
- The hover effect gives the false impression that the entire model card is interactive. This is not the case.
- The effect moves interactive elements around. It's only by a few pixels, but that can be enough for users to misclick, which is annoying because it's not their fault.
- Scaling does not work well with text rendering. Text is generally rendered to be grid aligned to be pixel perfect. This does not work well with smooth animations, so browsers disable grid aligned text rendering during animations to make them smooth. This has the side effect that text is noticeably less sharp during the animation. Less sharp text + moving text makes titles and descriptions harder to read.

**Comment by joeyballentine** [comment]
I tried doing it for just the images, but i couldn't get that to work. Maybe I'll try that again, because i still think it would be a cool effect, and it wouldn't cause the whole card to grow.

**Comment by joeyballentine** [comment]
ok, i had to merge in my changes from the other branch, but it now grows the images if they're paired and you hover over them. its an okay-ish effect but it still feels a bit odd

**Comment by RunDevelopment** [comment]
How married are we to this effect? Honestly, I think the image zoom in looks really weird. I mean, it essentially made #173 a feature... In general, I think any scale-type hover effect won't work well with comparison images, because we need (probably) pixel precision for them. This effect would look good if the thumbnail was a regular image, but I don't think it works for us.

**Pull request closed without merging**
